format = """
[](fg:color_white)\
[](fg:color_pink bg:color_white)\
[](fg:color_aqua bg:color_pink)\
[](fg:color_brown bg:color_aqua)\
[](fg:color_black bg:color_brown)\
[](fg:color_red bg:color_black)\
$os\
$username\
[](fg:color_red bg:color_orange)\
$hostname\
[](fg:color_orange bg:color_yellow)\
$directory\
[](bg:color_green fg:color_yellow)\
$git_branch\
[](bg:color_blue fg:color_green)\
$rust\
$dotnet\
$nodejs\
$php\
[](fg:color_blue bg:color_purple)\
$time\
[](fg:color_purple bg:color_background_darker)\
$character"""

palette = 'pride'

[palettes.pride]
color_text_light = '#fbf1c7'
color_background_dark = '#665c54'
color_background_darker = '#3c3836'
color_blue = '#0566bb'
color_aqua = '#73d7ee'
color_green = '#159915'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d0b011'
color_pink = '#fdafc7'
color_brown = '#603814'
color_white = '#ffffff'
color_black = '#000000'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_text_light bg:color_green)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_text_light bg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_background_darker"
format = '[[  $time ](fg:color_text_light bg:color_purple)]($style)'
