format = """
[](color_red)\
$os\
$username\
[](fg:color_red bg:color_orange)\
$hostname\
[](fg:color_orange bg:color_yellow)\
$directory\
[](bg:color_aqua fg:color_yellow)\
$git_branch\
[](bg:color_blue fg:color_aqua)\
$rust\
$dotnet\
$nodejs\
$php\
[](fg:color_blue bg:color_background_dark)\
[](fg:color_background_dark bg:color_background_darker)\
$time\
[ ](fg:color_background_darker)\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_text_light = '#fbf1c7'
color_background_dark = '#665c54'
color_background_darker = '#3c3836'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_text_light bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_text_light bg:color_aqua)]($style)'
